name: Deploy web + api to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: 22

defaults:
  run:
    working-directory: avans-keuzekompas

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: avans-keuzekompas/package-lock.json

      - run: npm ci --legacy-peer-deps

      - name: Build backend libs
        run: npx nx run-many --target=build --projects=backend-domain,backend-infrastructure,backend-application,backend-presentation --configuration=production --no-cloud

      - name: Build API (NestJS)
        run: npx nx run api:build --configuration=production --no-cloud

      # - name: Copy runtime dependencies and built libs to dist
      #   run: |
      #     cp package.json apps/backend/dist/
      #     cp package-lock.json apps/backend/dist/
      #     mkdir -p apps/backend/dist/libs
      #     cp -r dist/libs/* apps/backend/dist/libs/ || true
      #     cd apps/backend/dist
      #     npm ci --omit=dev --legacy-peer-deps

      - name: Install production deps in API dist (use generated package.json)
        run: |
          cd apps/backend/dist
          cat package.json
          # Add workspace libraries as file: dependencies so npm can install them from the built outputs
          jq '.dependencies = (.dependencies // {})
            | .dependencies["@avans-keuzekompas/domain"] = "file:../../libs/backend/domain"
            | .dependencies["@avans-keuzekompas/infrastructure"] = "file:../../libs/backend/infrastructure"
            | .dependencies["@avans-keuzekompas/application"] = "file:../../libs/backend/application"
            | .dependencies["@avans-keuzekompas/presentation"] = "file:../../libs/backend/presentation"
            | .dependencies["@avans-keuzekompas/types"] = "file:../../libs/shared/types"
            | .dependencies["@avans-keuzekompas/utils"] = "file:../../libs/shared/utils"' package.json > package.json.tmp
          mv package.json.tmp package.json
          # Install based on generated + augmented package.json
          npm install --omit=dev --legacy-peer-deps

      - name: Vendor workspace libs into node_modules (fallback)
        run: |
          # Ensure internal workspace packages exist under node_modules for runtime
          set -e
          mkdir -p apps/backend/dist/node_modules/@avans-keuzekompas
          for PKG in domain infrastructure application presentation; do
            if [ -f "apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/package.json" ]; then
              echo "Backend $PKG already present, skipping vendoring"
            else
              echo "Vendoring backend $PKG"
              rm -rf apps/backend/dist/node_modules/@avans-keuzekompas/$PKG
              mkdir -p apps/backend/dist/node_modules/@avans-keuzekompas/$PKG
              cp -R libs/backend/$PKG/dist apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/
              cp libs/backend/$PKG/package.json apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/package.json || true
            fi
          done
          for PKG in types utils; do
            if [ -f "apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/package.json" ]; then
              echo "Shared $PKG already present, skipping vendoring"
            else
              echo "Vendoring shared $PKG"
              rm -rf apps/backend/dist/node_modules/@avans-keuzekompas/$PKG
              mkdir -p apps/backend/dist/node_modules/@avans-keuzekompas/$PKG
              cp -R libs/shared/$PKG/dist apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/
              cp libs/shared/$PKG/package.json apps/backend/dist/node_modules/@avans-keuzekompas/$PKG/package.json || true
            fi
          done

      - name: Verify runtime modules exist in API dist
        run: |
          cd apps/backend/dist
          node -e "require.resolve('@nestjs/common'); require.resolve('@avans-keuzekompas/infrastructure'); require.resolve('@avans-keuzekompas/types'); console.log('Deps OK')"
          node -e "console.log('@nestjs/common version:', require('./node_modules/@nestjs/common/package.json').version)"
          if [ -d node_modules/@avans-keuzekompas/infrastructure ]; then echo "Found @avans-keuzekompas/infrastructure"; else echo "Missing @avans-keuzekompas/infrastructure"; fi
          if [ -d node_modules/@avans-keuzekompas/types ]; then echo "Found @avans-keuzekompas/types"; else echo "Missing @avans-keuzekompas/types"; fi

      - name: Ensure start scripts in API dist package.json
        run: |
          cd apps/backend/dist
          # Add both start and start:api for compatibility with App Service settings
          jq '.scripts = (.scripts // {})
            | .scripts.start = "node -e \"try{require.resolve(\\\"@nestjs/common\\\");require.resolve(\\\"@avans-keuzekompas/infrastructure\\\");process.exit(0)}catch(e){process.exit(1)}\" || npm install --omit=dev --legacy-peer-deps; node main.js"
            | .scripts["start:api"] = "node -e \"try{require.resolve(\\\"@nestjs/common\\\");require.resolve(\\\"@avans-keuzekompas/infrastructure\\\");process.exit(0)}catch(e){process.exit(1)}\" || npm install --omit=dev --legacy-peer-deps; node main.js"' package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Toon package.json en inhoud dist-map (debug)
        run: |
          echo "---- package.json ----"
          cat apps/backend/dist/package.json
          echo "---- inhoud dist ----"
          ls -l apps/backend/dist

      - name: Write API .env from GitHub secrets
        run: |
          set -e
          {
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}";
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}";
            # echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}";
          } > apps/backend/dist/.env
          echo "Wrote apps/backend/dist/.env"

      - name: Zip API artifact
        run: |
          cd apps/backend/dist
          zip -r "$GITHUB_WORKSPACE/api.zip" .
        shell: bash

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/api.zip

  build-and-deploy-web:
    needs: build-and-deploy-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: avans-keuzekompas/package-lock.json

      - run: npm ci --legacy-peer-deps

      - name: Inject NEXT_PUBLIC_API_URL for Web build
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > apps/frontend/.env.production

      - name: Build Web (Next.js)
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npx nx run web:build --configuration=production --no-cloud

      - name: Prepare Next.js deploy folder (standalone)
        run: |
          set -e
          rm -rf frontend-deploy
          mkdir -p frontend-deploy
          cp -R apps/frontend/.next/standalone/* frontend-deploy/
          mkdir -p frontend-deploy/apps/frontend/.next
          cp -R apps/frontend/.next/static frontend-deploy/apps/frontend/.next/static
          cp -R apps/frontend/public frontend-deploy/apps/frontend/public || true
          # Sanity check: in Nx monorepo staat server.js onder apps/frontend/
          ls -l frontend-deploy/apps/frontend | grep server.js || (echo "apps/frontend/server.js missing" && exit 1)

      - name: Add start script to standalone package.json (preserve deps)
        run: |
          # Gebruik het door Next.js gegenereerde package.json en voeg alleen een start script toe
          if [ ! -f frontend-deploy/package.json ]; then
            echo "Expected standalone package.json not found in frontend-deploy" >&2
            ls -la frontend-deploy || true
            exit 1
          fi
          jq '.scripts = (.scripts // {}) | .scripts.start = "node apps/frontend/server.js"' \
            frontend-deploy/package.json > frontend-deploy/package.json.tmp
          mv frontend-deploy/package.json.tmp frontend-deploy/package.json
          echo "Resulting package.json:" && cat frontend-deploy/package.json
          # Geen npm ci nodig; .next/standalone bevat node_modules

      - name: Verify Web runtime modules exist
        run: |
          cd frontend-deploy
          node -e "require.resolve('next'); require.resolve('react'); console.log('Web deps OK')"
          if [ -d node_modules/next ]; then echo "Found next"; else echo "Missing next" && exit 1; fi
          if [ -d node_modules/react ]; then echo "Found react"; else echo "Missing react" && exit 1; fi

      - name: Zip Web artifact
        run: |
          cd frontend-deploy
          zip -r "$GITHUB_WORKSPACE/web.zip" .
        shell: bash

      - name: Deploy Web to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/web.zip
