name: Deploy web + api to Azure Main.yml

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      - name: Build API (NestJS)
        run: npx nx run api:build --configuration=production

      - name: Zip API artifact
        run: |
          cd apps/backend/dist
          zip -r ../../../../api.zip .
        shell: bash

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: api.zip

  build-and-deploy-web:
    needs: build-and-deploy-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - run: npm ci --legacy-peer-deps

      - name: Build Web (Next.js)
        run: npx nx run web:build --configuration=production

      - name: Prepare Next.js deploy folder
        run: |
          mkdir -p frontend-deploy
          cp -R apps/frontend/.next frontend-deploy/.next
          cp -R apps/frontend/public frontend-deploy/public
          cp apps/frontend/package.json frontend-deploy/package.json
          cp apps/frontend/next.config.js frontend-deploy/next.config.js || true
        shell: bash

      - name: Zip Web artifact
        run: zip -r web.zip frontend-deploy
        shell: bash

      - name: Deploy Web to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEB_PUBLISH_PROFILE }}
          package: web.zip
